apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: project01acr.azurecr.io/app:c6bc948117399d9c2f21ddd0664ca81c75de9a16
        ports:
        - containerPort: 8000
