apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: project01acr.azurecr.io/app:3d97dd31dd0cc5dfd1cc15354ac8dbc71b75c4bf
        ports:
        - containerPort: 8000
